language: node_js
services: mongodb
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "npm run test_travis"
  - "npm run test_browser"
